### ISSUE TITLE
Fix "Add" profile form button position and text box styling

### ISSUE THREAD

**Issue by luisgamboa** [newmanix/itc260-sp15-gig-central#69]
It needs to be align to the right below the text box:

<img width="931" alt="screen shot 2016-05-24 at 1 36 37 pm" src="https://cloud.githubusercontent.com/assets/13126219/15519067/90e6384c-21b4-11e6-959e-17d4a85c9b02.png">

Also change the style for the text box:

    width: 444px;
    height: 115px;
    background-color: #ffffff;
    background-image: none;
    border: 1px solid #dce4ec;
    border-radius: 4px;
    -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
    -webkit-transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
    transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;

**Comment by MarioSeattle** [comment]
Hi Luis,

I worked on changing the color and floating the bottom to the right. 

http://www.seattletoursinspanish.com/gigcentral/profiles/add

I was thinking on leaving that right there so that I don't interfered on Turner's re do of the recapcha form. What are you thoughts ? Should I market this like fix and move on to something else ? Or should I get the form to behave responsively on mobile devices ? I want to double check before my first push!
